name: Deploy watsonx Orchestrate Agent

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ibm-watsonx-orchestrate

      - name: Configure watsonx Orchestrate environment
        env:
          WO_API_KEY: ${{ secrets.WO_API_KEY }}
          WO_URL: ${{ secrets.WO_URL }}
        run: |
          orchestrate env add -n production -u "$WO_URL"
          orchestrate env activate production --api-key "$WO_API_KEY"

      - name: Import tools
        run: |
          orchestrate tools import -k python -f tools/return_hello.py

      - name: Import agents
        run: |
          orchestrate agents import -f agents/hello-agent.yaml
